-- data:extend{
--     {
--         type = "item",
--         name = "wind-generator",
--         icon = "__PTech__/graphics/icons/wind-generator.png",
--         flags = {"goes-to-quickbar"},
--         subgroup = "energy",
--         order = "d-b",
--         place_result = "wind-generator",
--         stack_size = 5
--     },
--     {
--         type = "item",
--         name = "wind-generator-2",
--         icon = "__PTech__/graphics/icons/wind-generator.png",
--         flags = {"goes-to-quickbar"},
--         subgroup = "energy",
--         order = "d-b",
--         place_result = "wind-generator-2",
--         stack_size = 5
--     },
--     {
--         type = "item",
--         name = "wind-generator-3",
--         icon = "__PTech__/graphics/icons/wind-generator.png",
--         flags = {"goes-to-quickbar"},
--         subgroup = "energy",
--         order = "d-b",
--         place_result = "wind-generator-3",
--         stack_size = 5
--     },
--     {
--         type = "item",
--         name = "wind-generator-4",
--         icon = "__PTech__/graphics/icons/wind-generator.png",
--         flags = {"goes-to-quickbar"},
--         subgroup = "energy",
--         order = "d-b",
--         place_result = "wind-generator-4",
--         stack_size = 5
--     },
--     {
--         type = "item",
--         name = "wind-generator-5",
--         icon = "__PTech__/graphics/icons/wind-generator.png",
--         flags = {"goes-to-quickbar"},
--         subgroup = "energy",
--         order = "d-b",
--         place_result = "wind-generator-5",
--         stack_size = 5
--     },
-- }